# GitHub Pages configuration for AL FURSAN School
title: AL FURSAN - School Management System
description: A comprehensive school management system for AL FURSAN School - students, teachers, parents, and administrators
url: "https://yourusername.github.io"
baseurl: "/school-website"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Exclude files from processing
exclude:
  - README.md
  - LICENSE
  - .gitignore

# Enable GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-sitemap
